### ISSUE TITLE
Can't compile on Linux 6.12 kernel

### ISSUE THREAD

**Issue by KodzghlyCZ** [WCHSoftGroup/ch9344ser_linux#33]
When trying to compile on Linux 6.12, (6.12.11-1-MANJARO), I get this error

`make

make -C /lib/modules/6.12.11-1-MANJARO/build  M=/home/user/driver  

make[1]: Entering directory '/usr/lib/modules/6.12.11-1-MANJARO/build'

  CC [M]  /home/user/driver/ch9344.o

/home/user/driver/ch9344.c:65:10: fatal error: asm/unaligned.h: No such file or directory

   65 | #include <asm/unaligned.h>

      |          ^~~~~~~~~~~~~~~~~

compilation terminated.

make[3]: *** [scripts/Makefile.build:229: /home/user/driver/ch9344.o] Error 1

make[2]: *** [/usr/lib/modules/6.12.11-1-MANJARO/build/Makefile:1937: /home/user/driver] Error 2

make[1]: *** [Makefile:224: __sub-make] Error 2

make[1]: Leaving directory '/usr/lib/modules/6.12.11-1-MANJARO/build'

make: *** [Makefile:7: default] Error 2

`

I've noticed similar errors in similar projects, apparently it's caused by some changes in the 6.12 kernel.

**Comment by KodzghlyCZ** [comment]
Fixed in #34 , waiting for merge approval
